### ISSUE TITLE
Create a simple management web UI

### ISSUE THREAD

**Issue by ereslibre** [oneinfra/oneinfra#39]
Create a simple management web UI that will allow you users to:

* List, create and destroy clusters
* List, create and destroy components

Also, additionally, it should show how to manage worker node joins.

**Comment by PI-Victor** [comment]
i can help with this, if you're interested.

**Comment by ereslibre** [comment]
Hello @PI-Victor! Thank you for the offer! I will release the minimal UI I wrote in a couple of days. It's almost done, but I'm sure it can be improved a lot (I'm a React/Redux neophyte).

I'll ping you here when I publish it so you can have a look if you want to contribute.

Thank you!

**Comment by ereslibre** [comment]
This is done with the introduction of https://github.com/oneinfra/console and the documentation on how to deploy the console.
