### ISSUE TITLE
oi node join pre-flight checks

### ISSUE THREAD

**Issue by angelbarrera92** [oneinfra/oneinfra#56]
Hi!

I have faced some errors while joining a node.

If someone writes an incorrect runtime/image UNIX socket path the procedure does not fail at all but the node does not start properly because the configuration is not the right one.

As runtime/image UNIX socket existence can be tested before running the join procedure, it could be a good idea to do this check prior initialize the join procedure. 

What do you think?

**Comment by ereslibre** [comment]
Thank you @angelbarrera92! Certainly, this will be fixed in the next release.
