### ISSUE TITLE
Unable to see UI from browser

### ISSUE THREAD

**Issue by ashokpinapathula** [oneinfra/oneinfra#63]
**System information*

Unable to see UI from the browser but getting this response when hitting from server CLI
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><link href="/css/fa-all.css" rel="stylesheet"><link href="//fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet"><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="oneinfra console"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>oneinfra console</title><script>__AUTHENTICATION_METHODS__=["kubernetes-secrets"],0===__AUTHENTICATION_METHODS__.length?window.AUTHENTICATION_METHODS=["kubernetes-secrets"]:window.AUTHENTICATION_METHODS=__AUTHENTICATION_METHODS__</script><link href="/static/css/2.74189dbb.chunk.css" rel="stylesheet"><link href="/static/css/main.1a4980a0.chunk.css" rel="stylesheet"></head><body id="page-top" class="bg-gradient-primary"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,f,l=r[0],i=r[1],a=r[2],c=0,s=[];c<l.length;c++)f=l[c],Object.prototype.hasOwnProperty.call(o,f)&&o[f]&&s.push(o[f][0]),o[f]=0;for(n in i)Object.prototype.hasOwnProperty.call(i,n)&&(e[n]=i[n]);for(p&&p(r);s.length;)s.shift()();return u.push.apply(u,a||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,l=1;l<t.length;l++){var i=t[l];0!==o[i]&&(n=!1)}n&&(u.splice(r--,1),e=f(f.s=t[0]))}return e}var n={},o={1:0},u=[];function f(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,f),t.l=!0,t.exports}f.m=e,f.c=n,f.d=function(e,r,t){f.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(e,r){if(1&r&&(e=f(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)f.d(t,n,function(r){return e[r]}.bind(null,n));return t},f.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="/";var l=this.webpackJsonpfrontend=this.webpackJsonpfrontend||[],i=l.push.bind(l);l.push=r,l=l.slice();for(var a=0;a<l.length;a++)r(l[a]);var p=i;t()}([])</script><script src="/static/js/2.bc963f47.chunk.js"></script><script src="/static/js/main.ae58d20d.chunk.js"></script></

**Comment by ashokpinapathula** [comment]
closing

**Comment by ereslibre** [comment]
Hello @ashokpinapathula, is everything fine? Were you able to load the UI using the browser?

**Comment by ashokpinapathula** [comment]
No not able to see from browser

But from CLI can able to see some html response when I get
http://localhost:8000

**Comment by ereslibre** [comment]
@ashokpinapathula is your browser reporting any errors? The provided response looks correct.

What is your browser?

**Comment by ashokpinapathula** [comment]
Google Chrome and that is not installed in server
